/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*DELAY USING EXTERNAL TIM2 CODE FOR STM32F407-DISC1 MODEL*/
#include <stdint.h>
#include "stm32f407xx.h"

volatile uint32_t tim2_ms = 0;

/* ---------- LED INIT (PD13 – ORANGE LED) ---------- */
void LED_Init(void)
{
    RCC->AHB1ENR |= (1U << 3);            // GPIOD clock
    GPIOD->MODER &= ~(3U << (2 * 12));
        GPIOD->MODER |=  (1U << (2 * 12));
        GPIOD->MODER &= ~(3U << (2 * 13));
        GPIOD->MODER |=  (1U << (2 * 13));
        GPIOD->MODER &= ~(3U << (2 * 14));
        GPIOD->MODER |=  (1U << (2 * 14));
        GPIOD->MODER &= ~(3U << (2 * 15));
        GPIOD->MODER |=  (1U << (2 * 15));
}

/* ---------- TIM2 INIT (1ms interrupt) ---------- */
void TIM2_Init(void)
{
    RCC->APB1ENR |= (1 << 0);             // TIM2 clock

    TIM2->PSC = 16000 - 1;                // 1 ms tick
    TIM2->ARR = 1;                        // 1 ms period
    TIM2->CNT = 0;

    TIM2->EGR = 1;                        // Force update
    TIM2->SR  = 0;                        // Clear flags

    TIM2->DIER |= (1 << 0);               // Update interrupt
    TIM2->CR1  |= (1 << 0);               // Enable timer

    NVIC_EnableIRQ(TIM2_IRQn);
}

/* ---------- DELAY ---------- */
void delay_ms(uint32_t ms)
{
    uint32_t start = tim2_ms;
    while ((tim2_ms - start) < ms);
}

/* ---------- ISR ---------- */
void TIM2_IRQHandler(void)
{
    if (TIM2->SR & 1)
    {
        TIM2->SR &= ~1;                   // Clear UIF
        tim2_ms++;
    }
}

/* ---------- MAIN ---------- */
int main(void)
{
    LED_Init();
    TIM2_Init();

    while (1)
    {
    	GPIOD->ODR ^= (1U << 12);  // Toggle GREEN LED
    	        delay_ms(500);
    	        GPIOD->ODR ^= (1U << 12);
    	        GPIOD->ODR ^= (1U << 13);  // Toggle GREEN LED
    	         delay_ms(500);
    	         GPIOD->ODR ^= (1U << 13);
    			GPIOD->ODR ^= (1U << 14);  // Toggle GREEN LED
    			delay_ms(500);
    			GPIOD->ODR ^= (1U << 14);
    			GPIOD->ODR ^= (1U << 15);  // Toggle GREEN LED
    			delay_ms(500);

    }
}
