/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

volatile uint32_t sys_ms = 0;

/* ---------------- GPIO INIT ---------------- */
void led_Init(void)
{
    /* Enable GPIOD clock */
    RCC->AHB1ENR |= (1U << 3);   // GPIODEN

    /* PD12 as output */
    GPIOD->MODER &= ~(3U << (2 * 12));
    GPIOD->MODER |=  (1U << (2 * 12));
    GPIOD->MODER &= ~(3U << (2 * 13));
    GPIOD->MODER |=  (1U << (2 * 13));
    GPIOD->MODER &= ~(3U << (2 * 14));
    GPIOD->MODER |=  (1U << (2 * 14));
    GPIOD->MODER &= ~(3U << (2 * 15));
    GPIOD->MODER |=  (1U << (2 * 15));
}

/* ---------------- SYSTICK INIT ---------------- */
void SysTick_Init(void)
{
    SysTick->LOAD = 16000 - 1;   // 1 ms @ 16 MHz
    SysTick->VAL  = 0;
    SysTick->CTRL = (1U << 0) |  // ENABLE
                    (1U << 1) |  // TICKINT
                    (1U << 2);   // CPU clock
}

/* ---------------- SYSTICK ISR ---------------- */
void SysTick_Handler(void)
{
    sys_ms++;
}

/* ---------------- DELAY ---------------- */
void delay_ms(uint32_t ms)
{
    uint32_t start = sys_ms;
    while ((sys_ms - start) < ms);
}

/* ---------------- MAIN ---------------- */
int main(void)
{
    led_Init();
    SysTick_Init();

    while (1)
    {

        GPIOD->ODR ^= (1U << 12);  // Toggle GREEN LED
        delay_ms(500);
        GPIOD->ODR ^= (1U << 12);
        GPIOD->ODR ^= (1U << 13);  // Toggle GREEN LED
         delay_ms(500);
         GPIOD->ODR ^= (1U << 13);
		GPIOD->ODR ^= (1U << 14);  // Toggle GREEN LED
		delay_ms(500);
		GPIOD->ODR ^= (1U << 14);
		GPIOD->ODR ^= (1U << 15);  // Toggle GREEN LED
		delay_ms(500);
		GPIOD->ODR ^= (1U << 15);
    }
}
