/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif





/* ---------- GPIO INIT FOR SPI2 ---------- */
#include <stdint.h>
#include "stm32f407xx.h"

/* ---------- SPI2 GPIO INIT ---------- */
void SPI2_GPIO_Init(void)
{
    /* Enable GPIOB clock */
    RCC->AHB1ENR |= (1U << 1);

    /* ---------- PB13 (SCK), PB14 (MISO), PB15 (MOSI) → AF ---------- */
    GPIOB->MODER &= ~(0x3F << (13 * 2));
    GPIOB->MODER |=  (0x2A << (13 * 2));   // AF for 13,14,15

    /* ---------- PB12 → GPIO OUTPUT (Manual NSS) ---------- */
    GPIOB->MODER &= ~(3U << (2 * 12));
    GPIOB->MODER |=  (1U << (2 * 12));
    GPIOB->ODR   |=  (1U << 12);           // NSS HIGH (inactive)

    /* ---------- AF5 for SPI2 (PB13–PB15) ---------- */
    GPIOB->AFR[1] &= ~(0xFFF << 20);
    GPIOB->AFR[1] |=  (0x555 << 20);

    /* High speed */
    GPIOB->OSPEEDR |= (0x3F << (13 * 2));

    /* Push-pull */
    GPIOB->OTYPER &= ~(0xE << 13);

    /* No pull-up/down */
    GPIOB->PUPDR &= ~(0x3F << (13 * 2));
}

/* ---------- SPI2 INIT ---------- */
void SPI2_Init(void)
{
    /* Enable SPI2 clock */
    RCC->APB1ENR |= (1U << 14);

    /* Disable SPI */
    SPI2->CR1 &= ~(1U << 6);

    /* SPI configuration */
    SPI2->CR1 =
        (1U << 2)  |    // Master mode
        (0x3 << 3) |    // Baud rate = fPCLK / 16
        (1U << 9)  |    // SSM = software slave management
        (1U << 8);      // SSI = internal NSS HIGH

    /* Enable SPI */
    SPI2->CR1 |= (1U << 6);
}

/* ---------- SPI TRANSMIT (WITH NSS) ---------- */
void SPI2_Transmit(uint8_t data)
{
    /* NSS LOW → select slave */
    GPIOB->ODR &= ~(1U << 12);

    /* Wait TX buffer empty */
    while (!(SPI2->SR & (1U << 1)));

    *((volatile uint8_t *)&SPI2->DR) = data;

    /* Wait until SPI not busy */
    while (SPI2->SR & (1U << 7));

    /* NSS HIGH → deseclect slave */
    GPIOB->ODR |= (1U << 12);
}

/* ---------- MAIN ---------- */
int main(void)
{
    SPI2_GPIO_Init();
    SPI2_Init();

    while (1)
    {
        SPI2_Transmit(0xFF);     // Test byte
        for (volatile int i = 0; i < 500000; i++);
    }
}
