/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "stm32f446xx.h"
#include "led.h"
#include "uart.h"
#include "oskernel.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef uint32_t taskprofiler;
taskprofiler task0_profiler, task1_profiler, task2_profiler;

#define Quanta 10
void task0(void)
{
	while(1)
	{
		task0_profiler++;
	}

}

void task1(void)
{
	while(1)
	{
		task1_profiler++;
	}
}

void task2(void)
{
	while(1)
	{
		task2_profiler++;
	}
}

int main(void)
{
	oskernelInit();
	osKernelAddThreads(&task0,&task1,&task2);
	oskernelLaunch(Quanta);


}

void motorRun(void)
{
	printf("motor is starting\n\r");
}

void motorStop(void)
{
	printf("motor is stopping\n\r");
}

void ValveOpen(void)
{
	printf("Valve opening\n\r");
}

void ValveClose(void)
{
	printf("Valve closing\n\r");
}
